// Code generated by goctl. DO NOT EDIT.
// Source: shoppingCart.proto

package server

import (
	"context"

	"demo/shoppingcart-srv/internal/logic"
	"demo/shoppingcart-srv/internal/svc"
	"demo/shoppingcart-srv/shoppingCart"
)

type ShoppingCartServer struct {
	svcCtx *svc.ServiceContext
	shoppingCart.UnimplementedShoppingCartServer
}

func NewShoppingCartServer(svcCtx *svc.ServiceContext) *ShoppingCartServer {
	return &ShoppingCartServer{
		svcCtx: svcCtx,
	}
}

// 添加购物车
func (s *ShoppingCartServer) AddShoppingCart(ctx context.Context, in *shoppingCart.AddShoppingCartRequest) (*shoppingCart.AddShoppingCartResponse, error) {
	l := logic.NewAddShoppingCartLogic(ctx, s.svcCtx)
	return l.AddShoppingCart(in)
}

// 移除购物车
func (s *ShoppingCartServer) DeleteShoppingCart(ctx context.Context, in *shoppingCart.DeleteShoppingCartRequest) (*shoppingCart.DeleteShoppingCartResponse, error) {
	l := logic.NewDeleteShoppingCartLogic(ctx, s.svcCtx)
	return l.DeleteShoppingCart(in)
}

func (s *ShoppingCartServer) RemoveAllShoppingCart(ctx context.Context, in *shoppingCart.RemoveAllShoppingCartRequest) (*shoppingCart.RemoveAllShoppingCartResponse, error) {
	l := logic.NewRemoveAllShoppingCartLogic(ctx, s.svcCtx)
	return l.RemoveAllShoppingCart(in)
}
