// Code generated by goctl. DO NOT EDIT.
package types

type UserCaptchaReq struct {
	Mobile string `form:"mobile"`
}

type ForgetPasswordReq struct {
	Mobile      string `form:"mobile"`
	Captcha     string `form:"captcha"`
	UserId      int64  `form:"userId"`
	NewPassword string `form:"newPassword"`
}

type LoginUserReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type BindMobileReq struct {
	UserId int64  `form:"userId"`
	Mobile string `form:"mobile"`
}

type IdentityUserReq struct {
	UserId   int64  `form:"userId"`
	RealName string `form:"realName"`
	CardNo   string `form:"cardNo"`
}

type RelaseGoodsReq struct {
	GoodsTitle  string  `form:"goodsTitle"`
	GoodsPrice  float64 `form:"goodsPrice"`
	GoodsStock  int64   `form:"goodsStock"`
	GoodsStatus int64   `form:"goodsStatus"`
}

type GetGoodsInfoReq struct {
	GoodsId int64 `form:"goodsId"`
}

type AddShoppingCartReq struct {
	UserId     int64   `form:"userId"`
	GoodsId    int64   `form:"goodsId"`
	GoodsPrice float64 `form:"goodsPrice"`
	GoodsNum   int64   `form:"goodsNum"`
}

type DeleteShoppingCartReq struct {
	ShopId int64 `form:"shopId"`
}

type RemoveAllShoppingCartReq struct {
	UserId int64 `form:"userId"`
}

type CreateOrderReq struct {
	UserId      int64   `form:"userId"`
	GoodsId     int64   `form:"goodsId"`
	GoodsNum    int64   `form:"goodsNum"`
	TotalPrice  float64 `form:"totalPrice"`
	PayType     int64   `form:"payType"`
	OrderStatus int64   `form:"orderStatus"`
	RealName    string  `form:"realName"`
	Addr        string  `form:"addr"`
}

type AlipayReq struct {
	OrderId int64 `form:"orderId"`
}

type PayNotifyReq struct {
}

type PayNotifyResp struct {
}

type Response struct {
	Code    int64                  `json:"code"`
	Message string                 `json:"message"`
	Data    map[string]interface{} `json:"data"`
}
