// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: shoppingCart.proto

package shoppingCart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加购物车
type AddShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GoodsId    int64   `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	GoodsPrice float64 `protobuf:"fixed64,3,opt,name=GoodsPrice,proto3" json:"GoodsPrice,omitempty"`
	GoodsNum   int64   `protobuf:"varint,4,opt,name=GoodsNum,proto3" json:"GoodsNum,omitempty"`
}

func (x *AddShoppingCartRequest) Reset() {
	*x = AddShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppingCart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShoppingCartRequest) ProtoMessage() {}

func (x *AddShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingCart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*AddShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_shoppingCart_proto_rawDescGZIP(), []int{0}
}

func (x *AddShoppingCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddShoppingCartRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *AddShoppingCartRequest) GetGoodsPrice() float64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *AddShoppingCartRequest) GetGoodsNum() int64 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

type AddShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int64 `protobuf:"varint,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
}

func (x *AddShoppingCartResponse) Reset() {
	*x = AddShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppingCart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShoppingCartResponse) ProtoMessage() {}

func (x *AddShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingCart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*AddShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_shoppingCart_proto_rawDescGZIP(), []int{1}
}

func (x *AddShoppingCartResponse) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

// 移除购物车
type DeleteShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId int64 `protobuf:"varint,1,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
}

func (x *DeleteShoppingCartRequest) Reset() {
	*x = DeleteShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppingCart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShoppingCartRequest) ProtoMessage() {}

func (x *DeleteShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingCart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_shoppingCart_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteShoppingCartRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type DeleteShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong bool `protobuf:"varint,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *DeleteShoppingCartResponse) Reset() {
	*x = DeleteShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppingCart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShoppingCartResponse) ProtoMessage() {}

func (x *DeleteShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingCart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*DeleteShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_shoppingCart_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteShoppingCartResponse) GetPong() bool {
	if x != nil {
		return x.Pong
	}
	return false
}

// 清空购物车，返还总价格和数量，扣减虚拟库存
type RemoveAllShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *RemoveAllShoppingCartRequest) Reset() {
	*x = RemoveAllShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppingCart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAllShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllShoppingCartRequest) ProtoMessage() {}

func (x *RemoveAllShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingCart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_shoppingCart_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveAllShoppingCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveAllShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalPrice float64 `protobuf:"fixed64,1,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	Pong       bool    `protobuf:"varint,2,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *RemoveAllShoppingCartResponse) Reset() {
	*x = RemoveAllShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shoppingCart_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAllShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllShoppingCartResponse) ProtoMessage() {}

func (x *RemoveAllShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoppingCart_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_shoppingCart_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveAllShoppingCartResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *RemoveAllShoppingCartResponse) GetPong() bool {
	if x != nil {
		return x.Pong
	}
	return false
}

var File_shoppingCart_proto protoreflect.FileDescriptor

var file_shoppingCart_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61,
	0x72, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x31, 0x0a, 0x17, 0x41,
	0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x33,
	0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x68, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x68, 0x6f,
	0x70, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x36, 0x0a, 0x1c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41,
	0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x53, 0x0a,
	0x1d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x32, 0xc9, 0x02, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43,
	0x61, 0x72, 0x74, 0x12, 0x5e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x24, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x53,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x27, 0x2e, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72,
	0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x15,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x2a, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10,
	0x5a, 0x0e, 0x2e, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shoppingCart_proto_rawDescOnce sync.Once
	file_shoppingCart_proto_rawDescData = file_shoppingCart_proto_rawDesc
)

func file_shoppingCart_proto_rawDescGZIP() []byte {
	file_shoppingCart_proto_rawDescOnce.Do(func() {
		file_shoppingCart_proto_rawDescData = protoimpl.X.CompressGZIP(file_shoppingCart_proto_rawDescData)
	})
	return file_shoppingCart_proto_rawDescData
}

var file_shoppingCart_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shoppingCart_proto_goTypes = []interface{}{
	(*AddShoppingCartRequest)(nil),        // 0: shoppingCart.AddShoppingCartRequest
	(*AddShoppingCartResponse)(nil),       // 1: shoppingCart.AddShoppingCartResponse
	(*DeleteShoppingCartRequest)(nil),     // 2: shoppingCart.DeleteShoppingCartRequest
	(*DeleteShoppingCartResponse)(nil),    // 3: shoppingCart.DeleteShoppingCartResponse
	(*RemoveAllShoppingCartRequest)(nil),  // 4: shoppingCart.RemoveAllShoppingCartRequest
	(*RemoveAllShoppingCartResponse)(nil), // 5: shoppingCart.RemoveAllShoppingCartResponse
}
var file_shoppingCart_proto_depIdxs = []int32{
	0, // 0: shoppingCart.ShoppingCart.AddShoppingCart:input_type -> shoppingCart.AddShoppingCartRequest
	2, // 1: shoppingCart.ShoppingCart.DeleteShoppingCart:input_type -> shoppingCart.DeleteShoppingCartRequest
	4, // 2: shoppingCart.ShoppingCart.RemoveAllShoppingCart:input_type -> shoppingCart.RemoveAllShoppingCartRequest
	1, // 3: shoppingCart.ShoppingCart.AddShoppingCart:output_type -> shoppingCart.AddShoppingCartResponse
	3, // 4: shoppingCart.ShoppingCart.DeleteShoppingCart:output_type -> shoppingCart.DeleteShoppingCartResponse
	5, // 5: shoppingCart.ShoppingCart.RemoveAllShoppingCart:output_type -> shoppingCart.RemoveAllShoppingCartResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shoppingCart_proto_init() }
func file_shoppingCart_proto_init() {
	if File_shoppingCart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shoppingCart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppingCart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppingCart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppingCart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppingCart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAllShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shoppingCart_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAllShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shoppingCart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shoppingCart_proto_goTypes,
		DependencyIndexes: file_shoppingCart_proto_depIdxs,
		MessageInfos:      file_shoppingCart_proto_msgTypes,
	}.Build()
	File_shoppingCart_proto = out.File
	file_shoppingCart_proto_rawDesc = nil
	file_shoppingCart_proto_goTypes = nil
	file_shoppingCart_proto_depIdxs = nil
}
