// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: shoppingCart.proto

package shoppingCart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShoppingCart_AddShoppingCart_FullMethodName       = "/shoppingCart.ShoppingCart/AddShoppingCart"
	ShoppingCart_DeleteShoppingCart_FullMethodName    = "/shoppingCart.ShoppingCart/DeleteShoppingCart"
	ShoppingCart_RemoveAllShoppingCart_FullMethodName = "/shoppingCart.ShoppingCart/RemoveAllShoppingCart"
)

// ShoppingCartClient is the client API for ShoppingCart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoppingCartClient interface {
	// 添加购物车
	AddShoppingCart(ctx context.Context, in *AddShoppingCartRequest, opts ...grpc.CallOption) (*AddShoppingCartResponse, error)
	// 移除购物车
	DeleteShoppingCart(ctx context.Context, in *DeleteShoppingCartRequest, opts ...grpc.CallOption) (*DeleteShoppingCartResponse, error)
	RemoveAllShoppingCart(ctx context.Context, in *RemoveAllShoppingCartRequest, opts ...grpc.CallOption) (*RemoveAllShoppingCartResponse, error)
}

type shoppingCartClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingCartClient(cc grpc.ClientConnInterface) ShoppingCartClient {
	return &shoppingCartClient{cc}
}

func (c *shoppingCartClient) AddShoppingCart(ctx context.Context, in *AddShoppingCartRequest, opts ...grpc.CallOption) (*AddShoppingCartResponse, error) {
	out := new(AddShoppingCartResponse)
	err := c.cc.Invoke(ctx, ShoppingCart_AddShoppingCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingCartClient) DeleteShoppingCart(ctx context.Context, in *DeleteShoppingCartRequest, opts ...grpc.CallOption) (*DeleteShoppingCartResponse, error) {
	out := new(DeleteShoppingCartResponse)
	err := c.cc.Invoke(ctx, ShoppingCart_DeleteShoppingCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingCartClient) RemoveAllShoppingCart(ctx context.Context, in *RemoveAllShoppingCartRequest, opts ...grpc.CallOption) (*RemoveAllShoppingCartResponse, error) {
	out := new(RemoveAllShoppingCartResponse)
	err := c.cc.Invoke(ctx, ShoppingCart_RemoveAllShoppingCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingCartServer is the server API for ShoppingCart service.
// All implementations must embed UnimplementedShoppingCartServer
// for forward compatibility
type ShoppingCartServer interface {
	// 添加购物车
	AddShoppingCart(context.Context, *AddShoppingCartRequest) (*AddShoppingCartResponse, error)
	// 移除购物车
	DeleteShoppingCart(context.Context, *DeleteShoppingCartRequest) (*DeleteShoppingCartResponse, error)
	RemoveAllShoppingCart(context.Context, *RemoveAllShoppingCartRequest) (*RemoveAllShoppingCartResponse, error)
	mustEmbedUnimplementedShoppingCartServer()
}

// UnimplementedShoppingCartServer must be embedded to have forward compatible implementations.
type UnimplementedShoppingCartServer struct {
}

func (UnimplementedShoppingCartServer) AddShoppingCart(context.Context, *AddShoppingCartRequest) (*AddShoppingCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddShoppingCart not implemented")
}
func (UnimplementedShoppingCartServer) DeleteShoppingCart(context.Context, *DeleteShoppingCartRequest) (*DeleteShoppingCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteShoppingCart not implemented")
}
func (UnimplementedShoppingCartServer) RemoveAllShoppingCart(context.Context, *RemoveAllShoppingCartRequest) (*RemoveAllShoppingCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAllShoppingCart not implemented")
}
func (UnimplementedShoppingCartServer) mustEmbedUnimplementedShoppingCartServer() {}

// UnsafeShoppingCartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingCartServer will
// result in compilation errors.
type UnsafeShoppingCartServer interface {
	mustEmbedUnimplementedShoppingCartServer()
}

func RegisterShoppingCartServer(s grpc.ServiceRegistrar, srv ShoppingCartServer) {
	s.RegisterService(&ShoppingCart_ServiceDesc, srv)
}

func _ShoppingCart_AddShoppingCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddShoppingCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingCartServer).AddShoppingCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingCart_AddShoppingCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingCartServer).AddShoppingCart(ctx, req.(*AddShoppingCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingCart_DeleteShoppingCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShoppingCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingCartServer).DeleteShoppingCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingCart_DeleteShoppingCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingCartServer).DeleteShoppingCart(ctx, req.(*DeleteShoppingCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingCart_RemoveAllShoppingCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllShoppingCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingCartServer).RemoveAllShoppingCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingCart_RemoveAllShoppingCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingCartServer).RemoveAllShoppingCart(ctx, req.(*RemoveAllShoppingCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoppingCart_ServiceDesc is the grpc.ServiceDesc for ShoppingCart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingCart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoppingCart.ShoppingCart",
	HandlerType: (*ShoppingCartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddShoppingCart",
			Handler:    _ShoppingCart_AddShoppingCart_Handler,
		},
		{
			MethodName: "DeleteShoppingCart",
			Handler:    _ShoppingCart_DeleteShoppingCart_Handler,
		},
		{
			MethodName: "RemoveAllShoppingCart",
			Handler:    _ShoppingCart_RemoveAllShoppingCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppingCart.proto",
}
