// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"demo/goods-srv/goods"
	"demo/goods-srv/internal/logic"
	"demo/goods-srv/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

// 发布商品
func (s *GoodsServer) ReleaseGoods(ctx context.Context, in *goods.ReleaseGoodsRequest) (*goods.ReleaseGoodsResponse, error) {
	l := logic.NewReleaseGoodsLogic(ctx, s.svcCtx)
	return l.ReleaseGoods(in)
}

// 查看商品详情
func (s *GoodsServer) GetGoodsInfo(ctx context.Context, in *goods.GetGoodsInfoRequest) (*goods.GetGoodsInfoResponse, error) {
	l := logic.NewGetGoodsInfoLogic(ctx, s.svcCtx)
	return l.GetGoodsInfo(in)
}
