// Code generated by goctl. DO NOT EDIT.
// Source: shoppingCart.proto

package shoppingcartclient

import (
	"context"

	"demo/shoppingcart-srv/shoppingCart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddShoppingCartRequest        = shoppingCart.AddShoppingCartRequest
	AddShoppingCartResponse       = shoppingCart.AddShoppingCartResponse
	DeleteShoppingCartRequest     = shoppingCart.DeleteShoppingCartRequest
	DeleteShoppingCartResponse    = shoppingCart.DeleteShoppingCartResponse
	RemoveAllShoppingCartRequest  = shoppingCart.RemoveAllShoppingCartRequest
	RemoveAllShoppingCartResponse = shoppingCart.RemoveAllShoppingCartResponse

	ShoppingCart interface {
		// 添加购物车
		AddShoppingCart(ctx context.Context, in *AddShoppingCartRequest, opts ...grpc.CallOption) (*AddShoppingCartResponse, error)
		// 移除购物车
		DeleteShoppingCart(ctx context.Context, in *DeleteShoppingCartRequest, opts ...grpc.CallOption) (*DeleteShoppingCartResponse, error)
		RemoveAllShoppingCart(ctx context.Context, in *RemoveAllShoppingCartRequest, opts ...grpc.CallOption) (*RemoveAllShoppingCartResponse, error)
	}

	defaultShoppingCart struct {
		cli zrpc.Client
	}
)

func NewShoppingCart(cli zrpc.Client) ShoppingCart {
	return &defaultShoppingCart{
		cli: cli,
	}
}

// 添加购物车
func (m *defaultShoppingCart) AddShoppingCart(ctx context.Context, in *AddShoppingCartRequest, opts ...grpc.CallOption) (*AddShoppingCartResponse, error) {
	client := shoppingCart.NewShoppingCartClient(m.cli.Conn())
	return client.AddShoppingCart(ctx, in, opts...)
}

// 移除购物车
func (m *defaultShoppingCart) DeleteShoppingCart(ctx context.Context, in *DeleteShoppingCartRequest, opts ...grpc.CallOption) (*DeleteShoppingCartResponse, error) {
	client := shoppingCart.NewShoppingCartClient(m.cli.Conn())
	return client.DeleteShoppingCart(ctx, in, opts...)
}

func (m *defaultShoppingCart) RemoveAllShoppingCart(ctx context.Context, in *RemoveAllShoppingCartRequest, opts ...grpc.CallOption) (*RemoveAllShoppingCartResponse, error) {
	client := shoppingCart.NewShoppingCartClient(m.cli.Conn())
	return client.RemoveAllShoppingCart(ctx, in, opts...)
}
